---
title: "Predicting Lemur's Lifespan"
# subtitle: "My subtitle if needed"
author: 
  - Khushaal Nandwani
thanks: "Code and data are available at: [https://github.com/RohanAlexander/starter_folder](https://github.com/RohanAlexander/starter_folder)."
date: today
date-format: long
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
bibliography: ref.bib
editor:
  render-on-save: true
---
# Possible topics


# Introduction 
We are aiming to predict the lifepspan of a lemur. Specifically, using sex, specis, birth month of lemurs. We have also divided the dataset into two parts: one for lemurs in captivity and one for lemurs in wild. The goal is to realize the success we have achievd by captiving lemurs, see areas of improvement in the pre existing methods. 



1. What factors can contribute to lifespan of lemur?
    - sex
    - species
    - birth month (season): some seasons makes stronger. maybe winter?
    - captivity vs wild: captivity makes them use to spoon feeding?
    - litter size: maybe mother is more involved with other kids
    - mother_species and father_species is same or not

# Data
The data was taken from @cookson_duke_lemur_center, who acquired it from Duke Lemur Center more about which, can be found in Section [3.1](#data_collection). We used @citeR 

<!-- TODO: Add other libraries that were used -->

It is important to know about Lemurs and what affects their lifespan because they are the most endangered mammals on the planet. The Duke Lemur Center (DLC) is a global leader in the research, care, and conservation of lemurs. The DLC hosts the most diverse population of lemurs outside their native habitat in Madagascar.

To do so, I chose the following variables from the dataset, which I believe are the most important factors that can affect the lifespan of a lemur:

- `sex`: The sex of the lemur on birth. It is a cateogrical variable that can be `M` or `F`.
- `species`: The species of the lemur. It is also a categorical

<!-- Inclue genus from taxonomic code? -->

<!-- TODO: appendix me
- litter size par nirbhar hai
- maa baap same par nirbhar hai?
- agar pregnant hoti hai, toh kya age par fark aata hai?
 -->

## Data Collection {#data_collection}
The data in these sources was acquired and processed by staff at the Duke Lemur Center (DLC). 

### Data Acquisition
 As @3zehr points out, DLC staff collected data about the lemurs according to standard operating procedures and USDA, AZA, and IACUC guidelines. They recorded information about births, deaths, weights, enclosure moves, behaviors, and other significant events on a daily basis. Originally, this data was stored in handwritten and typed paper formats. Later, it was computerized. 

In the mid-1990s, the DLC started using two databases: the Animal Record Keeping System (ARKS) and MedARKS. These databases allowed the DLC to share information with other organizations through the International Species Information System (ISIS). The DLC is currently transitioning to using the Zoological Information Management System (ZIMS). Data not stored in these databases has been stored in spreadsheets, and the DLC is working on transferring data from older records into these databases.

### Data Processing
The DLC used SAS software to build a database for the lemur data. Data from various sources was imported into SAS Enterprise Guide, including ARKS, MedARKS, ZIMS, and spreadsheets. They wrote programs in SAS to extract, match, and join data, calculate new variables, and format the output. They also used tools within SAS Enterprise Guide Projects for calculations and formatting. The DLC uses a unique ID to match data for individual animals, and the taxonomic name for species-related variables. The data was validated by identifying and locating missing data, standardizing codes and text, investigating outliers, and comparing known values to the database output.Data that could not be verified was excluded from the published dataset. 

The DLC created two data files from the database: **the DLC Animal List**, which contains single-copy variables for each animal in the colony's history, and **the DLC Weight File**, which contains all weight measurements for each animal. We used the DLC Animal List for this analysis, which was first cleaned by @cookson_duke_lemur_center and then we clean it as per our needs.

The data in these sources was updated on February 8, 2019. The DLC plans to update the data on a yearly basis.


# Why Lemur?

Established in 1966 on Duke University's campus in Durham, NC, the Duke Lemur Center (DLC) is a global leader in the research, care, and conservation of lemurs, the planet's most endangered group of mammals. Home to over 200 animals spanning 13 species, the DLC hosts the most diverse population of lemurs outside their native habitat in Madagascar. cite(https://lemur.duke.edu)


\newpage 